### ISSUE TITLE
MemoryError: memory allocation failed

### ISSUE THREAD

**Issue by DmitriiCM** [iodeo/Socketel#1]
Hi and thanks for the cool project. 
I've tried to use it to connect Minitel 2 to the websocket server, alas without success:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "main.py", line 9, in <module>
  File "pages/menu_principal.py", line 17, in <module>
MemoryError: memory allocation failed, allocating 640 bytes

```

Brand new ESP32S board, I've tested also on the old ESP32. Board info:

```
>>> micropython.mem_info():

stack: 736 out of 15360
GC: total: 111168, used: 8720, free: 102448
No. of 1-blocks: 193, 2-blocks: 27, max blk sz: 24, max free sz: 6390

```
Any ideas?
Thanks.

**Comment by iodeo** [comment]
Hi,
Looks you have memory fractioning issue

Have you tried to change the order of the imports ?
What micropython framework are you using ?
And what is the old esp32 version ?
Mine was esp32 wroom32d

**Comment by DmitriiCM** [comment]
Thanks for the answer. My ESP32 is also from Wroom.

It looks like there is no error on Micropython v1.17, but the latest v1.19 does not work (which is weird, _mem_info_ shows similar values). Maybe it's fractioning indeed, thanks for the idea.

**Comment by iodeo** [comment]
Thanks for identifying the problem

I think I have used v1.18 without problem but never tried with v1.19. I will try once I found some time.. Please let us know if you find a fix on your side !
